{% set name = "jupyter-ai-magics" %}
{% set version = "2.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_ai_magics-{{ version }}.tar.gz
  sha256: 3237f744c4be2e5a1b48c6e6619b0e34158a8ab5eb45a62d6372d36b69b5be84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - pip
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - ipython
    - importlib-metadata >=5.2.0
    - langchain >=0.1.0,<0.3.0
    - langchain-community >=0.1.0,<0.3.0
    - typing-extensions >=4.5.0
    - click >=8.0,<9.dev0
    - jsonpath-ng >=1.5.3,<2

test:
  imports:
    - jupyter_ai_magics
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Jupyter AI magic commands
  home: https://github.com/jupyterlab/jupyter-ai
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JasonWeill
    - dlqqq
    - 3coins
    - andrii-i
